//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heconomy.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Heconomy.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   農業
        ///林業
        ///水産業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   銀行・信託業
        ///農水産金融業
        ///中小企業金融業
        ///金融附帯業
        ///投資業
        ///証券・商品取引
        ///保険業
        ///保険代理業
        ///不動産取引業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   不動産取引業
        ///不動産賃貸業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   物品賃貸業
        ///ホテル旅館
        ///家事サービス業
        ///洗濯・理容業
        ///他個人サービス
        ///映画業
        ///娯楽業
        ///放送業
        ///駐車場業
        ///自動車整備業
        ///その他修理業
        ///情報・広告業
        ///他事業サービス
        ///専門サービス業
        ///医療業
        ///廃棄物処理業
        ///他サービス業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   林業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   漁業
        ///水産養殖業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   金属鉱業
        ///石炭・亜炭鉱業
        ///原油・天然ガス鉱業
        ///非金属鉱業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   総合工事業
        ///職別工事業
        ///設備工事業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   食料品製造業
        ///飲料・飼料製造業
        ///繊維工業
        ///他繊維製品製造
        ///木材木製品製造
        ///家具・装備品
        ///パルプ・紙製造
        ///出版・印刷
        ///化学工業
        ///石油・石炭製品
        ///プラ製品製造業
        ///ゴム製品製造業
        ///革・毛皮製造業
        ///窯業・土石製品
        ///鋼鉄業
        ///非鉄金属製造業
        ///金属製品製造業
        ///一般機械器具
        ///電気機械器具
        ///輸送用機械器具
        ///精密機械器具
        ///武器製造業
        ///その他製造業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   電気業
        ///ガス業
        ///熱供給業
        ///水道業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   鉄道業
        ///道路旅客運送業
        ///道路貨物運送業
        ///水運業
        ///航空運輸業
        ///倉庫業
        ///運輸サービス
        ///通信業
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   各種商品卸売業
        ///繊・機・建材卸
        ///衣・職・家具卸
        ///代理商・仲介業
        ///各種商品小売業
        ///織物衣料小売業
        ///飲食料小売業
        ///自動車小売業
        ///家具建具小売業
        ///その他小売業
        ///一般飲食店
        ///その他飲食店
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
    }
}
